### ISSUE TITLE
Re-use some of your cmake files?

### ISSUE THREAD

**Issue by srappensperger** [HKUST-Robotics-Team/RTLib#2]
Hi, I'd like to re-use some of your cmake files in my own project.
Would you allow me to use them in my own project?
Or what would I have to do to include them in my project correctly (license)?

**Comment by Derppening** [comment]
For now, there is no mechanism to include this project in CMake, so feel free to use the `CMakeLists.txt`.

Between now and release 0.2.0 I will try to include the ability to `include(...)` this project into other CMake projects.

**Comment by srappensperger** [comment]
Thank you very much :D

**Comment by Derppening** [comment]
This issue has been fixed in branch `release/v0.2.0`, where users can now include RTLib directly from another CMake project.
